version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3008:3008"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./helper:/helper/db
    ports:
      - "27017:27017"